name: TagBot
on:
  workflow_dispatch:
    inputs:
      lookback:
        default: 3
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
    - uses: JuliaRegistries/TagBot@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
